version: "3.7"
services:
  mongobackup:
    image: mongobackup
    build: 
      context: .
      args:
        CRON: "* * * * *"
        MONGO_HOST: "<IP_MONGO_HERE>"
        MONGO_PORT: "<PORT_MONGO_HERE>"
        MONGO_PASSWD: "<PASSWORD_MONGO_HERE>"
        MONGO_USER: "<USER_MONGO_HERE>"
    restart: always
    volumes:
      - mongo-backup:/backups
volumes:
  mongo-backup:
