version: "3.7"
services:
  mongobackup:
    image: mongobackup
    build: 
      context: .
      args:
        CRON: "* * * * *"
        MONGO_HOST: "<IP_HERE>"
        MONGO_PORT: "27017"
        MONGO_PASSWD: "<PASSWORD_HERE>"
        MONGO_USER: "<USER_HERE>"
    restart: always
    volumes:
      - mongo-backup:/backups
volumes:
  mongo-backup:
  rcclone-config:
